# Your presentation title
title: Atelier Arduino

# Your presentation description (optional)
description: Atelier Arduino réalisé au CCSTI Grenoble le 2022-07-28

# Your name (optional)
author: Edgar Bonet

# The Reveal theme
reveal_theme: moon.css

# The Reveal transition
reveal_transition: none

# Path to the used theme (defaults to the Reveal.js standard theme path)
reveal_theme_path: reveal.js/css/theme/ 

# Additional custom CSS paths
extra_css: 

# Custom CSS for highlighting (defaults to reveal.js/lib/css/zenburn.css)
highlight_style_sheet: 

# Embed Server-side speaker notes?
reveal_notes_server: false

# Additional reveal.js options
reveal_options: 
  slideNumber: true
  width: 1920
  height: 1080

# Additional reveal.js dependencies
reveal_dependencies: 

# Reveal.js subdirectory
reveal_path: reveal.js/

# Exclude directories and/or files from the conversion
exclude:
  - Gemfile*
  - LICENSE
  - README.md

# Don't change anything below
markdown: kramdown
highlighter: rouge
markdown_ext: ignoreme

